Vagrant.configure("2") do |config|

    config.vm.define:mysql do |vmdb|
        vmdb.vm.box = "centos/7"
        vmdb.vm.network "private_network", ip: "192.168.11.16"
        vmdb.vm.network "forwarded_port", guest: 3306, host: 3306
        vmdb.vm.provider:virtualbox do |v|
            v.memory = 1024
            v.cpus = 1
        end
        vmdb.vm.provision "shell", path: "bootstrap.sh"
    end
end